<?php
 
if (!defined('XOOPS_ROOT_PATH')) {
	die('XOOPS root path not defined');	
}

// Main info
$modversion['name'] = _MI_CV_NAME;
$modversion['version'] = 1;
$modversion['description'] = _MI_CV_DESC;
$modversion['credits'] = 'Mohtava Project';
$modversion['author'] = 'Hossein Azizabadi';
$modversion['nickname'] = '';
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 1;
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "cv";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

// DB
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
$modversion['tables'][0] = "cv_project";
$modversion['tables'][1] = "cv_paper";
$modversion['tables'][2] = "cv_congress";
$modversion['tables'][3] = "cv_thesis";
$modversion['tables'][4] = "cv_profile_thesis";
$modversion['tables'][5] = "cv_profile_congress";
$modversion['tables'][6] = "cv_profile_paper";
$modversion['tables'][7] = "cv_profile_project";
$modversion['tables'][8] = "cv_profile_arbitration";
$modversion['tables'][9] = "cv_profile_journal";
$modversion['tables'][10] = "cv_profile";

//Admin things
$modversion['hasAdmin'] = 1;

// Menu
$modversion['hasMain'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Templates
$i = 1;
$modversion['templates'][$i]['file'] = 'cv_index.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'cv_profile.html';
$modversion['templates'][$i]['description'] = '';

?>