<?php
include 'admin_header.php';

xoops_cp_header();
if (video_checkModuleAdmin()){
    $permissions_admin = new ModuleAdmin();
    echo $permissions_admin->addNavigation('permissions.php');
}
$permission = isset($_POST['permission']) ? intval($_POST['permission']) : 1;$selected = array('','','','');$selected[$permission - 1]= ' selected';echo "<form method='post' name='fselperm' action='permissions.php'><table border='0'><tr><td><select name='permission' onChange='javascript: document.fselperm.submit()'><option value='1'".$selected[0].">"._AM_VIDEO_PERM_VIEW."</option><option value='2'".$selected[1].">"._AM_VIDEO_PERM_SUBMIT."</option><option value='3'".$selected[2].">"._AM_VIDEO_PERM_DOWNLOAD."</option><option value='4'".$selected[3].">"._AM_VIDEO_PERM_AUTRES."</option></select></td></tr><tr><td><input type='submit' name='go'></tr></table></form>";$moduleId = $xoopsModule->getVar('mid');switch($permission) {	case 1:	// View permission		$formTitle = _AM_VIDEO_PERM_VIEW;		$permissionName = 'video_view';		$permissionDescription = _AM_VIDEO_PERM_VIEW_DSC;		break;	case 2:	// Submit Permission		$formTitle = _AM_VIDEO_PERM_SUBMIT;		$permissionName = 'video_submit';		$permissionDescription = _AM_VIDEO_PERM_SUBMIT_DSC;		break;	case 3:	// Download Permission		$formTitle = _AM_VIDEO_PERM_DOWNLOAD;		if ($xoopsModuleConfig['permission_download'] == 1) {			$permissionDescription = _AM_VIDEO_PERM_DOWNLOAD_DSC;			$permissionName = 'video_download';		}else{			$permissionDescription = _AM_VIDEO_PERM_DOWNLOAD_DSC2;			$permissionName = 'video_download_item';		}		break;	case 4:		$formTitle = _AM_VIDEO_PERM_AUTRES;		$permissionName = "video_ac";		$permissionDescription = _AM_VIDEO_PERM_AUTRES_DSC;		$global_perms_array = array(	      '4' => _AM_VIDEO_PERMISSIONS_4 ,			'8' => _AM_VIDEO_PERMISSIONS_8 ,			'16' => _AM_VIDEO_PERMISSIONS_16 ,	      '32' => _AM_VIDEO_PERMISSIONS_32 ,			'64' => _AM_VIDEO_PERMISSIONS_64 ,
			'128' => _AM_VIDEO_PERMISSIONS_128		);		break;}

$permissionsForm = new XoopsGroupPermForm($formTitle, $moduleId, $permissionName, $permissionDescription, 'admin/permissions.php');if ($permission == 4){	foreach( $global_perms_array as $perm_id => $permissionName ) {		$permissionsForm->addItem($perm_id , $permissionName) ;	}}else{	if ($xoopsModuleConfig['permission_download'] == 2 && $permission == 3) {		$sql = "SELECT lid, cid, title FROM ".$xoopsDB->prefix("video_downloads")." ORDER BY title";		$result = $xoopsDB->query($sql);		if($result) {			while ($row = $xoopsDB->fetchArray($result)) {				$permissionsForm->addItem($row['lid'], $row['title']);			}		}	}else{		$sql = 'SELECT cat_cid, cat_pid, cat_title FROM '.$xoopsDB->prefix('video_cat').' ORDER BY cat_title';		$result = $xoopsDB->query($sql);		if($result) {			while ($row = $xoopsDB->fetchArray($result)) {				$permissionsForm->addItem($row['cat_cid'], $row['cat_title'], $row['cat_pid']);			}		}	}}echo $permissionsForm->render();echo "<br /><br /><br /><br />\n";unset ($permissionsForm);xoops_cp_footer();?>