<?php
// $Id: xoops_version.php,v 1.3 19:46 2010-01-06 Mazarin Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


$modversion['name'] = _MI_POLLS_NAME;
$modversion['version'] = 1.31;
$modversion['description'] = _MI_POLLS_DESC;
$modversion['author'] = "Created by Kazumi Ono ( http://www.myweb.ne.jp/ ), modified by Mazarin";
$modversion['credits'] = "";
$modversion['help'] = "poll.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "poll";
$modversion['min_php'] = '5.2';
$modversion['min_xoops'] = '2.5';




// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";



// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "poll_option";
$modversion['tables'][1] = "poll_desc";
$modversion['tables'][2] = "poll_log";



// Admin things
$modversion['system_menu'] = 1;
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['templates'][1]['file'] = 'poll_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'poll_view.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'poll_results.html';
$modversion['templates'][3]['description'] = '';

//Blocks
$modversion['blocks'][1]['file'] = "poll.php";
$modversion['blocks'][1]['name'] = _MI_POLLS_BNAME1;
$modversion['blocks'][1]['description'] = "Shows unlimited number of polls/surveys";
$modversion['blocks'][1]['show_func'] = "b_poll_show";
$modversion['blocks'][1]['template'] = 'poll_block_poll.html';

//config
$modversion['config'][0] = array(
  'name'      => "limit_by_ip" ,
  'title'     => '_MI_POLL_LIMITBYIP' ,
  'description' => '_MI_POLL_LIMITBYIPD' ,
  'formtype'    => 'yesno' ,
  'valuetype'   => 'int' ,
  'default'   => '1' ,
  'options'   => array()
) ;

//config
$modversion['config'][1] = array(
  'name'      => "limit_by_uid" ,
  'title'     => '_MI_POLL_LIMITBYUID' ,
  'description' => '_MI_POLL_LIMITBYUIDD' ,
  'formtype'    => 'yesno' ,
  'valuetype'   => 'int' ,
  'default'   => '0' ,
  'options'   => array()
) ;


// Menu
$modversion['hasMain'] = 1;

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'pollresults.php';
$modversion['comments']['itemName'] = 'poll_id';
?>